#makefile
#reseni projektu do IOS
#Autor: Martin Bobcik, xbobci00, FIT
#Date: Duben 2016

#parametry prekladu
cc = gcc
cflags = -std=gnu99 -Wall -Wextra -pedantic -lpthread -pthread -lrt

all:
	$(cc) $(cflags) main.c -o proj2

lacika:
    $(cc) $(cflags) xlacik02_proj2.c -o projLacika